on: push
concurrency: 
  cancel-in-progress: true
  group: main
jobs:
  dependencies:
    runs-on: ubuntu-latest
    name: Dependecies
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: actions/cache@v3
      id: node-dependecies
      with:
        path: ./node_modules/*
        key: ${{ github.sha }}
    - run: npm ci --legacy-peer-deps
  lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: ["dependencies"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: actions/cache@v3
      id: node-dependecies
      with:
        path: ./node_modules/*
        key: ${{ github.sha }}
    - run: npm run lint

  audit:
    runs-on: ubuntu-latest
    needs: ["dependencies"]
    name: Audit
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: actions/cache@v3
      id: node-dependecies
      with:
        path: ./node_modules/*
        key: ${{ github.sha }}
    - run: npm audit

  build-test:
    runs-on: ubuntu-latest
    name: Build (TEST)
    needs: ["dependencies", "audit", "lint"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: actions/cache@v3
      id: node-dependecies
      with:
        path: ./node_modules/*
        key: ${{ github.sha }}
    - run: npm run build